# Generated by Django 4.1.2 on 2024-01-24 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0002_lawyer_review_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('time', models.CharField(choices=[('7:00  - 8:00 ', '7:00  - 8:00'), ('8:00  - 9:00 ', '8:00  - 9:00'), ('9:00  - 10:00 ', '9:00  - 10:00'), ('10:00 - 11:00 ', '10:00 - 11:00'), ('11:00 - 12:00 ', '11:00 - 12:00'), ('12:00 - 13:00 ', '12:00 - 13:00'), ('13:00 - 14:00 ', '13:00 - 14:00'), ('14:00 - 15:00 ', '14:00 - 15:00'), ('15:00 - 16:00 ', '15:00 - 16:00'), ('16:00 - 17:00 ', '16:00 - 17:00'), ('17:00 - 18:00 ', '17:00 - 18:00')], max_length=50)),
                ('occupied', models.BooleanField(default=False)),
                ('waiting', models.BooleanField(default=False)),
                ('empty', models.BooleanField(default=True)),
                ('inavailable', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='cv',
            field=models.TextField(blank=True, default='lawyer'),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='facebook',
            field=models.URLField(blank=True, default='www.facebook.com', null=True),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='linkedin',
            field=models.URLField(blank=True, default='www.linkedin.com', null=True),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='phone',
            field=models.CharField(default='0000000000', max_length=10),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='twitter',
            field=models.URLField(blank=True, default='www.twitter.com', null=True),
        ),
    ]
