# Generated by Django 4.1.2 on 2024-01-25 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0004_googleuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='googleuser',
            old_name='test',
            new_name='name',
        ),
    ]
