# Generated by Django 4.1.2 on 2024-01-26 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0006_review_userr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='lawyer',
            new_name='lawyerr',
        ),
    ]
