# Generated by Django 4.1.2 on 2024-01-26 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0007_rename_lawyer_review_lawyerr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
