# Generated by Django 4.1.2 on 2024-01-26 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0010_alter_review_lawyerr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='lawyerr',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
