# Generated by Django 4.1.2 on 2024-01-26 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0012_alter_review_lawyerr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyer',
            name='profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
