# Generated by Django 4.1.2 on 2024-01-27 00:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0014_alter_calender_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='calender',
            name='law',
            field=models.ForeignKey(default=578, on_delete=django.db.models.deletion.CASCADE, related_name='cal', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
