# Generated by Django 4.1.2 on 2024-01-27 23:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0017_rename_empty_calender_empty_waiting_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField()),
                ('time', models.CharField(choices=[('7:00  - 8:00 ', '7:00  - 8:00'), ('8:00  - 9:00 ', '8:00  - 9:00'), ('9:00  - 10:00 ', '9:00  - 10:00'), ('10:00 - 11:00 ', '10:00 - 11:00'), ('11:00 - 12:00 ', '11:00 - 12:00'), ('12:00 - 13:00 ', '12:00 - 13:00'), ('13:00 - 14:00 ', '13:00 - 14:00'), ('14:00 - 15:00 ', '14:00 - 15:00'), ('15:00 - 16:00 ', '15:00 - 16:00'), ('16:00 - 17:00 ', '16:00 - 17:00'), ('17:00 - 18:00 ', '17:00 - 18:00')], max_length=50)),
                ('sent', models.BooleanField(default=True)),
                ('accepted', models.BooleanField(default=False)),
                ('google_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apps', to='tester.googleuser')),
                ('law', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
