# Generated by Django 4.1.2 on 2024-01-28 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0018_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=400)),
                ('date_created', models.DateField()),
                ('time', models.CharField(choices=[('7:00  - 8:00 ', '7:00  - 8:00'), ('8:00  - 9:00 ', '8:00  - 9:00'), ('9:00  - 10:00 ', '9:00  - 10:00'), ('10:00 - 11:00 ', '10:00 - 11:00'), ('11:00 - 12:00 ', '11:00 - 12:00'), ('12:00 - 13:00 ', '12:00 - 13:00'), ('13:00 - 14:00 ', '13:00 - 14:00'), ('14:00 - 15:00 ', '14:00 - 15:00'), ('15:00 - 16:00 ', '15:00 - 16:00'), ('16:00 - 17:00 ', '16:00 - 17:00'), ('17:00 - 18:00 ', '17:00 - 18:00')], max_length=50)),
                ('userr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revddd', to='tester.googleuser')),
            ],
        ),
    ]
