// import type { Metadata } from 'next'
"use client"
import { DefaultSeo } from 'next-seo';
import { Inter } from 'next/font/google'
import './globals.css'
import Authprovider from '@/components/providers/Authprovider'
import Navbar from './components/Navbar'
import global_en from '../public/translations/en/global.json'
import global_ar from '../public/translations/ar/global.json'
import i18next from 'i18next'
import { I18nextProvider,useTranslation } from 'react-i18next';

i18next.init({
  interpolation: {escapeValue: false},
  lng: "en",
  resources: {
    en: {
      global: global_en
    },
    ar: {
      global: global_ar
    }
  }

})

const inter = Inter({ subsets: ['latin'] })
// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) 
{

  return (
    <>
     <DefaultSeo
        titleTemplate="Create Next App"
        description={'Generated by create next app'}
      />
    <html lang="en">
      <body className={`${inter.className}  bg-black`}>
       <Authprovider>
          <I18nextProvider i18n={i18next}>
            {/* <Navbar className='z-20 ' />  */}
              {children}
          </I18nextProvider>
       </Authprovider>

      </body>
    </html>
    </>
    
  )
}
